#!/bin/bash

# Update the packages on your instance

 sudo yum update -y

# Install Docker

 sudo yum install docker -y

# Start the Docker Service

 sudo service docker start

# add the ec2 user to the docker group

 sudo usermod -a -G docker ec2-user
